
name: MacOS Test

env:
  flutter_version: "v1.12.13+hotfix.8"

on:
  push:
    branches:
      - master

jobs:
  flutter-test:
    timeout-minutes: 5
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Flutter
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: macos-latest-flutter-${{env.flutter_version}}
    - uses: subosito/flutter-action@v1
    - name: Install app dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
    - run: flutter build ios
